import localFont from "next/font/local";

import "./style/globals.css";
export const metadata = {
  title: "S-M",
  description: "Generated by create next app",
};
const sf = localFont({
  src: [
    {
      path: "fonts/sf-pro-text-light.woff",
      weight: "200",
      style: "normal",
    },
    {
      path: "fonts/sf-pro-text-light.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "fonts/sf-pro-text-regular.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "fonts/sf-pro-text-regular.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "fonts/sf-pro-text-medium.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "fonts/sf-pro-text-medium.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "fonts/sf-pro-text-semibold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "fonts/sf-pro-text-semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "fonts/sf-pro-text-bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "fonts/sf-pro-text-bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-sf",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={sf.variable}>
      <body>{children}</body>
    </html>
  );
}
