import localFont from "next/font/local";

import "./style/globals.css";
export const metadata = {
  title: "S-M",
  description: "Generated by create next app",
};
// const sf = localFont({
//   src: [
//     {
//       path: "fonts/SFPRODISPLAYTHINITALIC.OTF",
//       weight: "100",
//       style: "italic",
//     },
//     {
//       path: "fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF",
//       weight: "200",
//       style: "italic",
//     },
//     {
//       path: "fonts/SFPRODISPLAYLIGHTITALIC.OTF",
//       weight: "300",
//       style: "italic",
//     },
//     {
//       path: "fonts/SFPRODISPLAYREGULAR.OTF",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "fonts/SFPRODISPLAYMEDIUM.OTF",
//       weight: "500",
//       style: "normal",
//     },
//     {
//       path: "fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF",
//       weight: "600",
//       style: "italic",
//     },
//     {
//       path: "fonts/SFPRODISPLAYBOLD.OTF",
//       weight: "700",
//       style: "normal",
//     },
//     {
//       path: "fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF",
//       weight: "700",
//       style: "italic",
//     },
//     {
//       path: "fonts/SFPRODISPLAYBLACKITALIC.OTF",
//       weight: "900",
//       style: "italic",
//     },
//   ],
//   display: "swap",
//   variable: "--font-sf",
// });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
